pet_shelter_project/app_main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import main, contacts


urlpatterns = [
	path('', main, name='home'),
	path('contacts/', contacts, name='contacts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_shelter_project/pet_shelter_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


urlpatterns = [
    path('admin/', admin.site.urls),
	path('i18n', include('django.conf.urls.i18n')),
	path('api-auth/', include('rest_framework.urls')),
	path('', include('app_main.urls'), name='main'),
	path('', include('app_pets.urls'), name='pets'),
	path('', include('app_users.urls'), name='users'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_shelter_project/app_main/forms.py
from django import forms
from django.utils.translation import gettext as _


class SendMessageForm(forms.Form):
    from_email = forms.EmailField(label=_('Email'), required=True, help_text='Email')
    name = forms.CharField(label=_('Имя'), required=True)
    message = forms.CharField(label=_('Сообщение'), widget=forms.Textarea, required=True)

pet_shelter_project/app_main/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import SendMessageForm
from pet_shelter_project.settings import RECIPIENTS_EMAIL, EMAIL_HOST_USER
import logging

logger = logging.getLogger(__name__)


def main(request):
	return render(request, 'index.html')


def contacts(request):
	if request.method == 'GET':
		send_message_form = SendMessageForm()
		return render(request, 'contacts.html', context={'send_message_form': send_message_form})
	if request.method == 'POST':
		send_message_form = SendMessageForm(request.POST)
		if send_message_form.is_valid():
			name = send_message_form.cleaned_data['name']
			from_email = send_message_form.cleaned_data['from_email']
			message = send_message_form.cleaned_data['message']
			try:
				send_mail(f'от {name} {from_email}', message, EMAIL_HOST_USER, RECIPIENTS_EMAIL)
			except BadHeaderError:
				return HttpResponse('Ошибка')
			return redirect('/')
		return render(request, 'contacts.html', context={'send_message_form': send_message_form})

pet_shelter_project/app_main/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  {% block title %}
  <title>{% trans "Приложение для управления базой данных животных" %}</title>
  {% endblock title %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0, charset=UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/image_slide.js' %}"></script>
</head>

<body>
<div id="main">
  <!---Шапка--->
  <div id="header">
    <div class="header__content">
      <div>
        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <select class="custom_select" name="language">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
              {{ language.name_local }} ({{ language.code }})
            </option>
          {% endfor %}
        </select>
        <button class="btn" type="submit">{% trans "выбрать" %}</button>
      </form>
      </div>
      {% if request.user.is_authenticated %}
      <div style="display: flex;">
        <p class="header__name">{% trans "Привет" %} {{ request.user.username }}!</p>
        {% if request.user.is_superuser %}
        <div style="margin-right: 5px;">
          <button class="btn"><a href="/admin">{% trans "Админка" %}</a></button>
        </div>
        {% endif %}
        <div style="margin-right: 5px;">
          <button class="btn"><a href="/profile/{{ request.user.id }}">{% trans "Личный кабинет" %}</a></button>
        </div>
        <div>
          <button class="btn"><a href="/logout">{% trans "Выйти" %}</a></button>
        </div>
      </div>
      {% else %}
      <div style="display: flex;">
        <div style="margin-right: 5px;">
          <button class="btn"><a href="/registration">{% trans "Регистрация" %}</a></button>
        </div>
        <div>
          <button class="btn"><a href="/login">{% trans "Войти" %}</a></button>
        </div>
      </div>
      {% endif %}
    </div>
    <div class="navigation">
      <div id="welcome">
        <h1 class="title">{% trans "Приют питомцев" %}</h1>
      </div>
      <!--Меню-->
      <div id="menubar">
        {% block menu %}
        <ul id="menu">
          <li class="current"><a href="/">{% trans "Главная" %}</a></li>
          <li><a href="/catalog">{% trans "Животные" %}</a></li>
          {% if request.user.is_authenticated %}
          <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
          {% endif %}
          <li><a href="/contacts">{% trans "Контакты" %}</a></li>
        </ul>
        {% endblock menu %}
      </div>
      <!--Конец меню-->
    </div>
  </div>
  <!--Конец шапки-->
  <!---Контент--->
  <div id="site_content">
    <!---Текст--->
    {% block content %}
    <div id="text_content">

      <h2>{% trans "Волонтерский проект" %}</h2>
      <p>{% trans "Сайт приюта для бездомных животных создан на добровольной основе." %}<br />
      {% trans "Наша цель — помощь животным приюта и привлечение внимания к проблемам бездомных животных." %}<br />
      {% trans "В первую очередь, мы хотим помочь обрести нашим подопечным свой дом и хозяев." %}<br />
      {% trans "Животных много, хороших и несчастных! Давайте поможем безнадзорным животным вместе!" %}<br />
      {% trans "Спасите одну жизнь — возьмите домой средоточие радости и благодарности!" %}</p>

    </div>
    {% endblock content %}
    <!---Конец текст--->
    <!---Слайдер--->
    {% block slider %}
    <ul class="slideshow">
      <li class="show"><img width="500" height="450" src="{% static 'images/1.jpg' %}"/></li>
      <li><img width="500" height="450" src="{% static 'images/2.jpg' %}"/></li>
      <li><img width="500" height="450" src="{% static 'images/3.jpg' %}"/></li>
      <li><img width="500" height="450" src="{% static 'images/4.jpg' %}"/></li>
    </ul>
    <!---Конец слайдер--->
    {% endblock slider %}
  </div>
  <!--Конец контент-->
</div>

<div id="footer">
<!---Подвал--->
  <div class="footer_container">
    <div class="footer_container_box">
      <h2 align="center">{% trans "Блок левый" %}</h2>
      <p>{% trans "Дополнительное описание" %}</p>
      <a href="#">{% trans "Подробнее" %}</a>
    </div>
    <div class="footer_container_box">
      <h2 align="center">{% trans "Блок средний" %}</h2>
      <p>{% trans "Дополнительное описание" %}</p>
      <a href="#">{% trans "Подробнее" %}</a>
    </div>
    <div class="footer_container_boxl">
      <h2 align="center">{% trans "Блок правый" %}</h2>
      <p>{% trans "Дополнительное описание" %}</p>
      <a href="#">{% trans "Подробнее" %}</a>
    </div>
  </div>
  <div class="footer_links">
    <a href="/">{% trans "Приют питомцев" %}</a> | <a href="/api/pets">{% trans "API" %}</a> | <a href="/contacts">{% trans "Контакты" %}</a>
  </div>

<!---Конец подвал--->
</div>

</body>
</html>

pet_shelter_project/app_main/templates/contacts.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li class="current"><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}
	
{% block content %}
  <div id="text_content">
      <h2>{% trans "Страница обратной связи" %}</h2>
      <div class="contact-text">
        <h3>{% trans "Контактные данные" %}</h3>

        <div class="address-text">
          <p><span>{% trans "Адрес:" %}</span>{% trans "Russia, Red Square, 1" %}</p>
        </div>
        <div class="phone-text">
          <p><span>{% trans "Тел.:" %}</span> +X-xxx-xxx-1111</p>
        </div>
        <div class="email-text">
          <p><span>{% trans "Email:" %}</span> test@mail.ru</p>
        </div>
      </div>
      <div class="contact-text">
        <h3>{% trans "Напишите нам" %}</h3>
          <div class="contact_from">
            <form class="form_settings" action="/contacts/" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <input  class="form_input" type="text" name="name" required="" id="id_name" placeholder="{% trans 'Имя' %}">
              <input class="form_input" type="email" name="from_email" required="" id="id_from_email" placeholder="{% trans 'Email' %}">
              <textarea class="form_t_area" name="message" cols="40" rows="10" required="" id="id_message" placeholder="{% trans 'Сообщение' %}"></textarea>
              <button class="btn" type="submit">{% trans "Отправить" %}</button>
            </form>
          </div>
      </div>
      <div class="contact-text">
        <h3>{% trans "Соцсети" %}</h3>
        <a class="social-link" href="https://vk.com/28kulikov">
          <img src="{% static 'images/svg/VK.svg' %}">
        </a>
        <a class="social-link" href="https://t.me/kulikov_av">
          <img src="{% static 'images/svg/Tg.svg' %}">
        </a>
        <a class="social-link" href="#">
          <img src="{% static 'images/svg/Whatsapp.svg' %}">
        </a>
      </div>
   </div>
{% endblock content %}

pet_shelter_project/app_main/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block menu %}
<ul id="menu">
  <li class="current"><a href="/">{% trans "Главная" %}</a></li>
  <li><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}