pet_shelter_project/app_main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import main, contacts


urlpatterns = [
	path('', main, name='home'),
	path('contacts/', contacts, name='contacts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_shelter_project/app_pets/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import CatalogListView, CatalogDetailView, UpdatePet, AddPet, catalog, unpublished_list, unpublished, delete
from .api import PetList
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'api/pets', PetList)

urlpatterns = [
	path('catalog/', catalog, name='catalog_list_types'),
	path('catalog/unpublished/', unpublished_list, name='unpublished_list'),
	path('catalog/unpublished/pet/<int:pk>', unpublished, name='unpublished_detail'),
	path('catalog/<int:type_id>', CatalogListView.as_view(), name='list_pets'),
	path('catalog/pet/<int:pk>', CatalogDetailView.as_view(), name='detail_pet'),
	path('catalog/pet/<int:pk>/update_pet/', UpdatePet.as_view(), name='update_pet'),
	path('add_pet', AddPet.as_view(), name='add_pet'),
	path('catalog/pet/<int:pk>/delete', delete, name='delete_pet'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + router.urls

pet_shelter_project/pet_shelter_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


urlpatterns = [
    path('admin/', admin.site.urls),
	path('i18n', include('django.conf.urls.i18n')),
	path('api-auth/', include('rest_framework.urls')),
	path('', include('app_main.urls'), name='main'),
	path('', include('app_pets.urls'), name='pets'),
	path('', include('app_users.urls'), name='users'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_shelter_project/app_pets/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from PIL import Image


class PetType(models.Model):

	title = models.CharField(max_length=30, verbose_name=_('тип животного'))

	def __str__(self):
		return self.title


class File(models.Model):
	file = models.ImageField(upload_to='files/%Y-%m-%d')
	created_at = models.DateField(auto_now_add=True)

	def save(self, *args, **kwargs):
		super(File, self).save(*args, **kwargs)

		if self.file:
			filename = self.file.path
			image = Image.open(filename)
			image = image.resize((229, 167), Image.ANTIALIAS)
			image.save(filename)

	def __str__(self):
		return self.file.path


class PetModel(models.Model):

	name = models.CharField(max_length=30, db_index=True, verbose_name=_('кличка животного'))
	type = models.ForeignKey(PetType, on_delete=models.CASCADE, verbose_name=_('тип животного'), default=None, null=True)
	age = models.PositiveIntegerField(db_index=True, verbose_name=_('возраст животного'))
	date_from = models.DateField(verbose_name=_('дата прибытия в приют'))
	weight = models.PositiveIntegerField(verbose_name=_('вес животного'))
	growth = models.PositiveIntegerField(db_index=True, verbose_name=_('рост животного'))
	special_signs = models.CharField(max_length=200, db_index=True, verbose_name=_('особые приметы животного'))
	published = models.BooleanField(default=False, verbose_name=_('опубликовать'))
	file = models.ForeignKey(File, on_delete=models.CASCADE, verbose_name=_('фото животного'), default=None, null=True)

	def __str__(self):
		return self.name

pet_shelter_project/app_pets/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import PetModel


class AddPetForm(forms.ModelForm):
	class Meta:
		model = PetModel
		fields = ['name', 'type', 'age', 'date_from', 'weight', 'growth', 'special_signs']


class UploadFileForm(forms.Form):
	file = forms.FileField(required=False)


class UpdatePetForm(forms.ModelForm):
	class Meta:
		model = PetModel
		fields = ['name', 'type', 'age', 'date_from', 'weight', 'growth', 'special_signs', 'published']


class PublishedForm(forms.Form):
	published = forms.BooleanField(required=False, widget=forms.CheckboxInput)

pet_shelter_project/app_pets/views.py
from django.shortcuts import render, redirect
from django.views import generic, View
from .models import PetType, PetModel, File
from .forms import AddPetForm, UploadFileForm, UpdatePetForm, PublishedForm
from django.http import HttpResponseBadRequest, HttpResponseForbidden


class CatalogListView(View):

	@staticmethod
	def get(request, type_id):
		pets = PetModel.objects.select_related('file').filter(type_id=type_id)
		return render(request, 'catalog_list_pets.html', context={'pets': pets})


class CatalogDetailView(View):

	@staticmethod
	def get(request, pk):
		pet = PetModel.objects.select_related('file').get(id=pk)
		return render(request, 'catalog_detail_pet.html', context={'pet': pet})


class UpdatePet(View):

	@staticmethod
	def get(request, pk):
		pet = PetModel.objects.get(id=pk)
		pet_form = UpdatePetForm(instance=pet)
		file_form = UploadFileForm()
		return render(request, 'update_pet.html', context={'pet_form': pet_form, 'file_form': file_form, 'pk': pk})

	@staticmethod
	def post(request, pk):
		if request.user.is_authenticated:
			pet = PetModel.objects.get(id=pk)
			pet_form = UpdatePetForm(request.POST)
			file_form = UploadFileForm(request.POST, request.FILES)
			if pet_form.is_valid():
				pet.name = pet_form.cleaned_data.get('name')
				pet.type = pet_form.cleaned_data.get('type')
				pet.age = pet_form.cleaned_data.get('age')
				pet.date_from = pet_form.cleaned_data.get('date_from')
				pet.weight = pet_form.cleaned_data.get('weight')
				pet.growth = pet_form.cleaned_data.get('growth')
				pet.special_signs = pet_form.cleaned_data.get('special_signs')
				pet.published = pet_form.cleaned_data.get('published')
				if file_form.is_valid() and request.FILES.getlist('file'):
					file = request.FILES.getlist('file')[0]
					file_object = File(file=file)
					file_object.save()
					pet.file = file_object
				pet.save()
			else:
				return HttpResponseBadRequest('что-то неправильно ввели')
		else:
			return HttpResponseForbidden('нет прав пользователя')
		return redirect('/')


class AddPet(View):

	@staticmethod
	def get(request):
		pet_form = AddPetForm()
		file_form = UploadFileForm()
		return render(request, 'add_pet.html', context={'pet_form': pet_form, 'file_form': file_form})

	@staticmethod
	def post(request):
		if request.user.is_authenticated:
			pet_form = AddPetForm(request.POST)
			file_form = UploadFileForm(request.POST, request.FILES)
			if pet_form.is_valid():
				name = pet_form.cleaned_data.get('name')
				type = pet_form.cleaned_data.get('type')
				age = pet_form.cleaned_data.get('age')
				date_from = pet_form.cleaned_data.get('date_from')
				weight = pet_form.cleaned_data.get('weight')
				growth = pet_form.cleaned_data.get('growth')
				special_signs = pet_form.cleaned_data.get('special_signs')
				file_object = None
				if file_form.is_valid() and request.FILES.getlist('file'):
					file = request.FILES.getlist('file')[0]
					file_object = File(file=file)
					file_object.save()

				PetModel.objects.create(name=name, type=type, age=age, date_from=date_from, weight=weight,
										growth=growth, special_signs=special_signs, file=file_object)
				return redirect('/')
			else:
				return HttpResponseBadRequest('что-то неправильно ввели')
		else:
			return HttpResponseForbidden('нет прав пользователя')


def catalog(request):
	titles = PetType.objects.values_list('title', flat=True)
	if 'Кошки' not in titles:
		PetType.objects.create(title='Кошки')
	if 'Собаки' not in titles:
		PetType.objects.create(title='Собаки')
	context = PetType.objects.all()
	return render(request, 'catalog_list_types.html', {'context': context})


def delete(request, pk):
	if request.method == 'GET':
		if request.user.is_superuser:
			pet = PetModel.objects.get(id=pk)
			pet.delete()
		else:
			return HttpResponseForbidden('нет прав')
		return redirect('/')
	else:
		return HttpResponseBadRequest('что-то не так')


def unpublished_list(request):
	pets = PetModel.objects.select_related('file').filter(published=False)
	published_form = PublishedForm()
	if request.method == 'POST':
		if request.user.is_superuser:
			if request.POST.getlist('published'):
				for pet in pets:
					pet.published = True
				pets.bulk_update(pets, ['published'])
				return redirect('/')
		else:
			return HttpResponseForbidden('нет прав администратора')
	return render(request, 'unpublished_list.html', context={'pets': pets, 'published_form': published_form})


def unpublished(request, pk):
	data = PetModel.objects.select_related('file').get(id=pk)
	published_form = PublishedForm()
	if request.method == 'POST':
		if request.user.is_superuser:
			if request.POST.getlist('published'):
				pet = PetModel.objects.get(id=pk)
				pet.published = True
				pet.save()
				return redirect('/')
		else:
			return HttpResponseForbidden('нет прав администратора')
	return render(request, 'unpublished.html', context={'pet': data, 'published_form': published_form})

pet_shelter_project/app_pets/templates/add_pet.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li class="current"><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}
<div id="text_content">
  <h2>{% trans "Добавить питомца" %}</h2>
    <form method="post" action="/add_pet" enctype="multipart/form-data">
      {% csrf_token %}
      <p>{% trans "Кличка" %} - {{ pet_form.name }}</p>
      <p>{% trans "Тип" %} - {{ pet_form.type }}</p>
      <p>{% trans "Возраст" %} - {{ pet_form.age }}</p>
      <p>{% trans "Дата прибытия" %} - {{ pet_form.date_from }}</p>
      <p>{% trans "Вес" %} - {{ pet_form.weight }}</p>
      <p>{% trans "Рост" %} - {{ pet_form.growth }}</p>
      <p>{% trans "Особые приметы" %} - {{ pet_form.special_signs }}</p>
      <p>{% trans "Фото" %} - {{ file_form.file }}</p>
      <button class="btn" type="submit">{% trans "Добавить" %}</button>
    </form>
</div>
{% endblock content %}

pet_shelter_project/app_pets/templates/catalog_detail_pet.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li class="current"><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}
<div id="text_content">
<h2>{% trans "Карточка животного" %}</h2>
<div class="pet_card pet_card_detail">
  <img class="pet_card_img" src="/media/{{ pet.file.file }}">
  <p>{{ pet.name }}</p>
  <p>{{ pet.special_signs }}</p>
</div>
{% if request.user.is_superuser %}
<button class="btn"><a href="{{ pet.id }}/update_pet">{% trans "Редактировать" %}</a></button>
<button class="btn"><a href="{{ pet.id }}/delete">{% trans "Удалить" %}</a></button>
{% elif request.user.is_authenticated %}
<button class="btn"><a href="{{ pet.id }}/update_pet">{% trans "Редактировать" %}</a></button>
{% endif %}

</div>
{% endblock content %}

pet_shelter_project/app_pets/templates/catalog_list_pets.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li class="current"><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}

<h2 class="pet_cards_title">{% trans "Каталог животных" %}</h2>
<div>
<div id="catalog">
  <ul class="pet_cards">
    {% for pet in pets %}
    {% if pet.published %}
    <li class="pet_card">
      <a href="pet/{{ pet.id }}">
        <img class="pet_card_img" src="/media/{{ pet.file.file }}">
        <p>{{ pet.name }}</p>
        <p>{{ pet.special_signs }}</p>
      </a>
    </li>
    {% endif %}
    {% endfor %}
  </ul>

</div>
</div>
{% endblock content %}

{% block slider %}
{% endblock slider %}

pet_shelter_project/app_pets/templates/catalog_list_types.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li class="current"><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}
<div id="text_content">
<h2>{% trans "Каталог животных" %}</h2>
<div id="catalog">
  <ul id="catalog__menu">
    {% for value in context %}
    <li><a href="{{ value.id }}">{{ value.title }}</a></li>
    {% endfor %}
    {% if request.user.is_superuser %}
    <li><a href="unpublished/">неопубликованные</a></li>
    {% endif %}
  </ul>
</div>
</div>
{% endblock content %}

pet_shelter_project/app_pets/templates/unpublished.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li class="current"><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}

<h2 class="pet_cards_title">{% trans "Каталог неопубликованных животных" %}</h2>

<div id="catalog">
  <div class="contact_from">
    <form class="form_published" action="/catalog/unpublished/pet/{{ pet.id }}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="checkbox" name="published" id="id_published">
      <button class="btn" type="submit">{% trans "Опубликовать" %}</button>
    </form>
  </div>
  <div class="pet_cards pet_card_published">
    <div class="pet_card">
      <img class="pet_card_img" src="/media/{{ pet.file.file }}">
      <p>{{ pet.name }}</p>
      <p>{{ pet.special_signs }}</p>
    </div>
  </div>
</div>

{% endblock content %}

{% block slider %}
{% endblock slider %}

pet_shelter_project/app_pets/templates/unpublished_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
  <li class="current"><a href="/catalog">{% trans "Животные" %}</a></li>
  {% if request.user.is_authenticated %}
  <li><a href="/add_pet">{% trans "Добавить" %}</a></li>
  {% endif %}
  <li><a href="/contacts">{% trans "Контакты" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}

<h2 class="pet_cards_title">{% trans "Каталог неопубликованных животных" %}</h2>

<div id="catalog">
  <div class="contact_from">
  <form class="form_published" action="/catalog/unpublished/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="checkbox" name="published" id="id_published">
    <button class="btn" type="submit">{% trans "Опубликовать всех" %}</button>
  </form>
  </div>
  <ul class="pet_cards">
    {% for pet in pets %}
    <li class="pet_card">
      <a href="pet/{{ pet.id }}">
        <img class="pet_card_img" src="/media/{{ pet.file.file }}">
        <p>{{ pet.name }}</p>
        <p>{{ pet.special_signs }}</p>
      </a>
    </li>
    {% endfor %}
  </ul>

</div>
</div>
{% endblock content %}

{% block slider %}
{% endblock slider %}

pet_shelter_project/app_pets/templates/update_pet.html
{% extends "base.html" %}
{% load i18n %}

{% block menu %}
<ul id="menu">
  <li><a href="/">{% trans "Главная" %}</a></li>
</ul>
{% endblock menu %}

{% block content %}
<div id="text_content">
  <h2>{% trans "Редактирование" %}</h2>
    <form method="post" action="/catalog/pet/{{ pk }}/update_pet/" enctype="multipart/form-data">
      {% csrf_token %}
      <p>{% trans "Кличка" %} - {{ pet_form.name }}</p>
      <p>{% trans "Тип" %} - {{ pet_form.type }}</p>
      <p>{% trans "Возраст" %} - {{ pet_form.age }}</p>
      <p>{% trans "Дата прибытия" %} - {{ pet_form.date_from }}</p>
      <p>{% trans "Вес" %} - {{ pet_form.weight }}</p>
      <p>{% trans "Рост" %} - {{ pet_form.growth }}</p>
      <p>{% trans "Особые приметы" %} - {{ pet_form.special_signs }}</p>
      <p>{% trans "Фото" %} - {{ file_form.file }}</p>
      {% if request.user.is_superuser %}
      <p>{% trans "Опубликовано" %} - {{ pet_form.published }}</p>
      {% endif %}
      <button class="btn" type="submit">{% trans "Редактировать" %}</button>
    </form>
</div>
{% endblock content %}